name: Python application

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Create Test File Inline
      run: |
        echo "import unittest
        def validar_estado(estado):
            return estado.lower() == 'active'
        class TestVuelos(unittest.TestCase):
            def test_pasa(self):
                self.assertTrue(validar_estado('active'))
        if __name__ == '__main__':
            unittest.main()" > test_final.py
    - name: Run Test
      run: python test_final.py
